version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pms-backend
    restart: always
    volumes:
      - backend-data:/app/data
    ports:
      - "8001:8000"
    environment:
      - SECRET_KEY=your_secure_secret_key_here

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=/
    container_name: pms-frontend
    restart: always
    ports:
      - "81:80"
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pms-frontend.rule=Host(`istmo.ohmaishoot.com`)"
      - "traefik.http.routers.pms-frontend.entrypoints=websecure"
      - "traefik.http.routers.pms-frontend.tls=true"
      - "traefik.http.routers.pms-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.pms-frontend.loadbalancer.server.port=80"

volumes:
  backend-data:
